
export const SET_CURRENT_USER =  'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER='CLEAR_CURRENT_USER';
export const SET_FAIL_MESSAGE= 'SET_FAIL_MESSAGE';
export const CLEAR_FAIL_MESSAGE = 'CLEAR_FAIL_MESSAGE';